
API_KEY_RSI = 'bg_0b01ffa94b4b6f3c2ba5df488587a91e'
API_SECRET_RSI = 'facbe7d57bbfb8c6fd82a39d2ce5dc35eef578058ec667aa5ad2fc02dffa644a'
API_PASSWORD = '9025014840'

API_KEY = 'bg_6153231782d4239653d4fec1f5e98a96'
API_SECRET = 'a9081277d3e96cdca97b1e3d93f5d3760ae5dc76cb9a7960e429f838c01cd102'

TELEGRAM_TOKEN_RSI = '8066951467:AAHOaFDL9kixcdwtjbwb-szDgnl8R9Vz8AI'

TELEGRAM_TOKEN = '7426543281:AAHu4Qf_KT6sGBaqUJU5ccFKZroHKrVc9R0'

TELEGRAM_CHAT_ID = '1385370555'
CHAT_ID = '1385370555'

SELECTED_SYMBOLS = ["1000000MOGUSDT", "1000RATSUSDT", "1000SATSUSDT", "1000XECUSDT", "1INCHUSDT", "1MBABYDOGEUSDT", 
"AAVEUSDT", "ACHUSDT", "ADAUSDT", "AERGOUSDT", "AGLDUSDT", "ALPHAUSDT", "ANKRUSDT", "APEUSDT", "APTUSDT", "ARKMUSDT", "ARPAUSDT", "ARUSDT", "ASTRUSDT", "ATAUSDT", "ATHUSDT", "AVAXUSDT", "AXSUSDT", "AEROUSDT", "ACTUSDT", 
"BANANAUSDT", "BBUSDT", "BCHUSDT", "BELUSDT", "BICOUSDT", "BIGTIMEUSDT", "BLASTUSDT", "BNBUSDT", "BRETTUSDT", "BTCUSDT", "BANUSDT", 
"C98USDT", "CATIUSDT", "CELRUSDT", "CHESSUSDT", "CHZUSDT", "CLOUDUSDT", "COMPUSDT", "COSUSDT", "COTIUSDT", "CRVUSDT", "CTSIUSDT", "CVCUSDT", "CYBERUSDT", "COWUSDT", "CETUSUSDT", "CATSUSDT", "CARVUSDT", "CROUSDT", 
"DARUSDT", "DEGENUSDT", "DENTUSDT", "DIAUSDT", "DOGEUSDT", "DOGUSDT", "DOTUSDT", "DYMUSDT", "DBRUSDT", "DIRFTUSDT", 
"EIGENUSDT", "ENAUSDT", "ENJUSDT", "EOSUSDT", "ETHUSDT", "ETHWUSDT", 
"FETUSDT", "FIDAUSDT", "FILUSDT", "FLUXUSDT", "FTMUSDT", "FTNUSDT", "FXSUSDT", "FWOGUSDT", "FOXYUSDT", 
"GALAUSDT", "GMCI30USDT", "GMXUSDT", "GOATUSDT", "GRTUSDT", "GTCUSDT", "GUSDT", "HMSTRUSDT", "HOOKUSDT", "HOTUSDT", "HIPPOUSDT", 
"ICPUSDT", "ICXUSDT", "IDUSDT", "IMXUSDT", "IOSTUSDT", "IOTAUSDT", "JOEUSDT", "JUPUSDT", 
"KASUSDT", "KAVAUSDT", "KMNOUSDT", "KNCUSDT", "KSMUSDT", "KAIAUSDT", 
"LEVERUSDT", "LINKUSDT", "LISTAUSDT", "LITUSDT", "LOOKSUSDT", "LPTUSDT", "LQTYUSDT", "LRCUSDT", "LTCUSDT", "LUMIAUSDT", "LUNAUSDT", 
"MAGICUSDT", "MANAUSDT", "MANTAUSDT", "MASKUSDT", "MAVIAUSDT", "METISUSDT", "MEWUSDT", "MKRUSDT", "MOODENGUSDT", "MOVRUSDT", "MYROUSDT", "MTLUSDT", "MERLUSDT", 
"NEARUSDT", "NEIROCTOUSDT", "NEIROUSDT", "NEOUSDT", "NFPUSDT", "NKNUSDT", "NOTUSDT", "NTRNUSDT", "NULSUSDT", 
"OGUSDT", "OMNI1USDT", "ONDOUSDT", "ONEUSDT", "OPUSDT", "ORBSUSDT", "ORDERUSDT", "ORDIUSDT", "OLUSDT", 
"PAXGUSDT", "PENDLEUSDT", "PEOPLEUSDT", "PHBUSDT", "POLYXUSDT", "PONKEUSDT", "POPCATUSDT", "PORTALUSDT", "POWRUSDT", "PUFFERUSDT", "PYTHUSDT", "PYRUSDT", "PNUTUSDT", "PROSUSDT", "PEAQUSDT", 
"QNTUSDT", "QTUMUSDT", "QUICKUSDT", "RAYUSDT", "REIUSDT", "REZUSDT", "RPLUSDT", "RUNEUSDT", "RVNUSDT", "RADUSDT", "RIFSOLUSDT", 
"SAGAUSDT", "SANTOSUSDT", "SEIUSDT", "SFPUSDT", "SHIBUSDT", "SKLUSDT", "SNXUSDT", "SOLUSDT", "SPELLUSDT", "SPXUSDT", "SSVUSDT", "STGUSDT", "STGUSDT", "STMXUSDT", "STXUSDT", "SUIUSDT", "SUSHIUSDT", "SYNUSDT", "SYSUSDT", "SWELLUSDT", "SMILEUSDT", "SAFEUSDT", "SCRUSDT", "SLERFUSDT", "SWEATUSDT", "SNTUSDT", "STEEMUSDT", 
"TAOUSDT", "TIAUSDT", "TROYUSDT", "TRUUSDT", "TRXUSDT", "TURBOUSDT", "TUSDT", 
"UMAUSDT", "UNIUSDT", "UXLINKUSDT", "VOXELUSDT", "VIRTUALUSDT", 
"WAXPUSDT", "WIFUSDT", "WLDUSDT", "XRPUSDT", "XUSDT", "ZETAUSDT", "ZILUSDT", "ZKJUSDT", "ZROUSDT"
]
#, "GRASSUSDT", , "10000WHYUSDT",  "DEEPUSDT",
